spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-payment
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase.1/changelog-master.yml

client:
  MicroServicesProject:
    endpoint: localhost:8082

